# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:23
from __future__ import unicode_literals
from django.db import migrations

import sys


def prepare_test_env1():
    if 'test'in sys.argv:
        sql = '''
            CREATE SCHEMA IF NOT EXISTS "Dengue_global";
            CREATE SCHEMA IF NOT EXISTS "Municipio";

            CREATE TABLE IF NOT EXISTS "Dengue_global"."Municipio"
            (
              geocodigo integer NOT NULL,
              nome character varying(128) NOT NULL,
              geojson text NOT NULL,
              populacao bigint NOT NULL,
              uf character varying(20) NOT NULL,
              CONSTRAINT "Municipio_pk" PRIMARY KEY (geocodigo)
            );

            INSERT INTO "Dengue_global"."Municipio" (
                geocodigo, nome, geojson, populacao, uf
            ) VALUES(
                3304557, 'Rio de Janeiro', '', 6498837, 'Rio de Janeiro'
            );
        '''
    else:
        sql = 'SELECT 1;'

    return migrations.RunSQL(sql, hints={'target_db': 'dados'})


class Migration(migrations.Migration):
    app_label = 'gis'
    initial = True

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                prepare_test_env1()
            ],
        )
    ]
