# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:23
from __future__ import unicode_literals

from django.db import migrations
from ..settings import BASE_DIR

import os
import sys


def create_table_satellite_climate():
    path = os.path.dirname(BASE_DIR)
    path = os.path.join(path, 'sql', 'create_table_satellite_climate.sql')

    with open(path) as f:
        sql = f.read()

    return migrations.RunSQL(sql, hints={'target_db': 'dados'})


class Migration(migrations.Migration):
    """

    """
    app_label = 'gis'

    dependencies = [
        ('gis', '0001_prepare_test_env1'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                create_table_satellite_climate()
            ],
        )
    ]