# Generated by Django 2.0.1 on 2018-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0002_create_table_satellite_climate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteClimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_date', models.DateField(db_column='images_date', help_text='Data das imagens')),
                ('ndvi', models.FloatField(db_column='ndvi', help_text='Valor médio NDVI', null=True)),
                ('temperature_max', models.FloatField(db_column='temperature_max', help_text='Valor médio de Temperatura Máxima', null=True)),
                ('temperature_min', models.FloatField(db_column='temperature_min', help_text='Valor médio Temperatura Mínima', null=True)),
                ('precipitation', models.FloatField(db_column='precipitation', help_text='Valor médio de Precipitação', null=True)),
                ('relative_humidity', models.FloatField(db_column='relative_humidity', help_text='Valor médio de Umidade Relativa', null=True)),
                ('specific_humidity', models.FloatField(db_column='specific_humidity', help_text='Valor médio de Umidade Específica', null=True)),
            ],
            options={
                'verbose_name_plural': 'satellite_climates',
                'db_table': 'Municipio"."satellite_climate',
                'managed': False,
            },
        ),
    ]
